### PR TITLE
Fix: Handle missing home environment

### LINKED ISSUE #17: Urgent: Don't Depend on HOME Being Set
```javascript
2016-01-11T13:16:57.382Z	959bee10-b865-11e5-8b87-752e23b3a9b9	TypeError: Arguments to path.join must be strings at path.js:360:15 at Array.filter (native) at exports.join (path.js:358:36) at expandHomeDir (/var/task/node_modules/stormpath/node_modules/stormpath-config/node_modules/expand-home-dir/index.js:10:10) at new LoadAPIKeyConfigStrategy (/var/task/node_modules/stormpath/node_modules/stormpath-config/lib/strategy/LoadAPIKeyConfigStrategy.js:14:19) at module.exports (/var/task/node_modules/stormpath/lib/configLoader.js:17:5) at new Client (/var/task/node_modules/stormpath/lib/Client.js:43:45) at Response.<anonymous> (/var/task/stormpath_loader.js:21:26) at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:354:18) at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
```

We need to modify our loading code to ensure that $HOME is not depended on -- this will ensure that our library works in environments where this variable isn't present (docker, AWS, etc.).

We need to get this fixed ASAP for a user.

### PR DESCRIPTION
**Pull request by typerandom**
Fixes #17.

### CODE REVIEW

File: lib/helpers.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
+'use strict';
```
Comment (timothyej) [inline lib/helpers.js]: It would be nicer to place this file in `lib/helpers/expand-home-dir.js` instead of a generic *helper* file :)

File: lib/helpers.js [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+    if (homeDir) {
+      if (path === '~') {
+        return homeDir;
+      }
+
+      if (path.slice(0, 2) !== '~/') {
+        return path;
+      }
+    } else {
```
Comment (timothyej) [inline lib/helpers.js]: You could've done `if (!homeDir)` instead, and this `else` would not be as hidden down here, and it would also have reduced some indentation :)

File: lib/helpers.js [hunk 3]
```diff
@@ -0,0 +1,28 @@
+'use strict';
+
+var join = require('path').join;
+
+module.exports = {
+  expandHomeDir: function (path) {
```
Comment (timothyej) [inline lib/helpers.js]: Please name functions of this importance, so it's easier to debug in the future. And if you would rename this file to only contain one helper function, you could export that function only.

**Comment by typerandom** [comment]
@timothyej Thanks! Really good feedback.

Really needed to fix this issue so didn't focus on those things you mentioned. But they are good for the future so I incorporated them in a new PR :)

https://github.com/stormpath/stormpath-node-config/pull/19

Cheers! :beers:
